name: batik_explorer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/lg_batik.png"

flutter:
  uses-material-design: true

  assets:
    - asset/images/

  fonts:
    - family: Oxygen
      fonts:
        - asset: asset/font/Oxygen/Oxygen-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: asset/font/Staatliches/Staatliches-Regular.ttf
